pipeline:
  prepare:
    image: node:8.11.0-alpine
    commands:
      - npm install
  lint:
    image: node:8.11.0-alpine
    commands:
      - npm run lint
  npm audit:
    image: node:8.11.0-alpine
    commands:
      - npm install -g npm@6.9.0
      - npm audit

 deploy to integration:
    image: jch254/docker-node-serverless
    commands:
      - serverless deploy --stage dev
    when:
      event: tag

deploy to production:
    image: jch254/docker-node-serverless
    commands:
      - serverless deploy --stage prod
    when:
      event: deployment
      environment: production

